require("core.plugins_config.gruvbox")
require("core.plugins_config.lsp")
require("core.plugins_config.lualine")
require("core.plugins_config.telescope")
require("core.plugins_config.treesitter")
require("core.plugins_config.completion")
require("core.plugins_config.harpoon")
